# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/wb/workspace/pyside/Tools/life/ui/c11x5Widget.ui'
#
# Created: Mon Jun 30 17:08:57 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_c11x5Widget(object):
    def setupUi(self, c11x5Widget):
        c11x5Widget.setObjectName("c11x5Widget")
        c11x5Widget.resize(800, 619)
        self.centralwidget = QtGui.QWidget(c11x5Widget)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabhirstorydata = QtGui.QWidget()
        self.tabhirstorydata.setObjectName("tabhirstorydata")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabhirstorydata)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget_history = QtGui.QTableWidget(self.tabhirstorydata)
        self.tableWidget_history.setObjectName("tableWidget_history")
        self.tableWidget_history.setColumnCount(0)
        self.tableWidget_history.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tableWidget_history)
        self.tabWidget.addTab(self.tabhirstorydata, "")
        self.tabstatisticdata = QtGui.QWidget()
        self.tabstatisticdata.setObjectName("tabstatisticdata")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabstatisticdata)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_statistic = QtGui.QTableWidget(self.tabstatisticdata)
        self.tableWidget_statistic.setObjectName("tableWidget_statistic")
        self.tableWidget_statistic.setColumnCount(0)
        self.tableWidget_statistic.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidget_statistic)
        self.tabWidget.addTab(self.tabstatisticdata, "")
        self.tabglobaloccurrencestatistic = QtGui.QWidget()
        self.tabglobaloccurrencestatistic.setObjectName("tabglobaloccurrencestatistic")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tabglobaloccurrencestatistic)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget_global_occurrencestatistic = QtGui.QTableWidget(self.tabglobaloccurrencestatistic)
        self.tableWidget_global_occurrencestatistic.setObjectName("tableWidget_global_occurrencestatistic")
        self.tableWidget_global_occurrencestatistic.setColumnCount(0)
        self.tableWidget_global_occurrencestatistic.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget_global_occurrencestatistic)
        self.tabWidget.addTab(self.tabglobaloccurrencestatistic, "")
        self.tabselectedoccurrencestatistic = QtGui.QWidget()
        self.tabselectedoccurrencestatistic.setObjectName("tabselectedoccurrencestatistic")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabselectedoccurrencestatistic)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget_selected_occurrencestatistic = QtGui.QTableWidget(self.tabselectedoccurrencestatistic)
        self.tableWidget_selected_occurrencestatistic.setObjectName("tableWidget_selected_occurrencestatistic")
        self.tableWidget_selected_occurrencestatistic.setColumnCount(0)
        self.tableWidget_selected_occurrencestatistic.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.tableWidget_selected_occurrencestatistic)
        self.tabWidget.addTab(self.tabselectedoccurrencestatistic, "")
        self.tabdrawcanvas = QtGui.QWidget()
        self.tabdrawcanvas.setObjectName("tabdrawcanvas")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tabdrawcanvas)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_canvas = QtGui.QFrame(self.tabdrawcanvas)
        self.widget_canvas.setFrameShape(QtGui.QFrame.StyledPanel)
        self.widget_canvas.setFrameShadow(QtGui.QFrame.Raised)
        self.widget_canvas.setObjectName("widget_canvas")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_canvas)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6.addWidget(self.widget_canvas)
        self.tabWidget.addTab(self.tabdrawcanvas, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        c11x5Widget.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(c11x5Widget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menu_system = QtGui.QMenu(self.menubar)
        self.menu_system.setObjectName("menu_system")
        self.menu_plot = QtGui.QMenu(self.menubar)
        self.menu_plot.setObjectName("menu_plot")
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        c11x5Widget.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(c11x5Widget)
        self.statusbar.setObjectName("statusbar")
        c11x5Widget.setStatusBar(self.statusbar)
        self.action_exit = QtGui.QAction(c11x5Widget)
        self.action_exit.setObjectName("action_exit")
        self.action_plotRepeatNumber = QtGui.QAction(c11x5Widget)
        self.action_plotRepeatNumber.setObjectName("action_plotRepeatNumber")
        self.action_about = QtGui.QAction(c11x5Widget)
        self.action_about.setObjectName("action_about")
        self.action_startAnalyse = QtGui.QAction(c11x5Widget)
        self.action_startAnalyse.setObjectName("action_startAnalyse")
        self.action_analyze_selected = QtGui.QAction(c11x5Widget)
        self.action_analyze_selected.setObjectName("action_analyze_selected")
        self.action_draw_sample = QtGui.QAction(c11x5Widget)
        self.action_draw_sample.setObjectName("action_draw_sample")
        self.action_select_from_yestorday = QtGui.QAction(c11x5Widget)
        self.action_select_from_yestorday.setObjectName("action_select_from_yestorday")
        self.action_distribution_analyze = QtGui.QAction(c11x5Widget)
        self.action_distribution_analyze.setObjectName("action_distribution_analyze")
        self.action_analyze_selected_distribution_local = QtGui.QAction(c11x5Widget)
        self.action_analyze_selected_distribution_local.setObjectName("action_analyze_selected_distribution_local")
        self.action_analyze_selected_distribution_global = QtGui.QAction(c11x5Widget)
        self.action_analyze_selected_distribution_global.setObjectName("action_analyze_selected_distribution_global")
        self.action_draw_distribution_animation = QtGui.QAction(c11x5Widget)
        self.action_draw_distribution_animation.setObjectName("action_draw_distribution_animation")
        self.action_select_by_global = QtGui.QAction(c11x5Widget)
        self.action_select_by_global.setObjectName("action_select_by_global")
        self.action_select_by_local = QtGui.QAction(c11x5Widget)
        self.action_select_by_local.setObjectName("action_select_by_local")
        self.menu_system.addAction(self.action_exit)
        self.menu_plot.addAction(self.action_plotRepeatNumber)
        self.menu_plot.addAction(self.action_distribution_analyze)
        self.menu_plot.addAction(self.action_analyze_selected_distribution_local)
        self.menu_plot.addAction(self.action_analyze_selected_distribution_global)
        self.menu_plot.addAction(self.action_draw_distribution_animation)
        self.menu_plot.addSeparator()
        self.menu_plot.addAction(self.action_draw_sample)
        self.menu_help.addAction(self.action_about)
        self.menu.addAction(self.action_startAnalyse)
        self.menu.addAction(self.action_analyze_selected)
        self.menu.addAction(self.action_select_from_yestorday)
        self.menu.addAction(self.action_select_by_global)
        self.menu.addAction(self.action_select_by_local)
        self.menubar.addAction(self.menu_system.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_plot.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(c11x5Widget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(c11x5Widget)

    def retranslateUi(self, c11x5Widget):
        c11x5Widget.setWindowTitle(QtGui.QApplication.translate("c11x5Widget", "C11x5", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabhirstorydata), QtGui.QApplication.translate("c11x5Widget", "历史数据", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabstatisticdata), QtGui.QApplication.translate("c11x5Widget", "统计数据", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabglobaloccurrencestatistic), QtGui.QApplication.translate("c11x5Widget", "全局重复次数", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabselectedoccurrencestatistic), QtGui.QApplication.translate("c11x5Widget", "选择行分析", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabdrawcanvas), QtGui.QApplication.translate("c11x5Widget", "图表", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_system.setTitle(QtGui.QApplication.translate("c11x5Widget", "系统", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_plot.setTitle(QtGui.QApplication.translate("c11x5Widget", "绘图", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_help.setTitle(QtGui.QApplication.translate("c11x5Widget", "帮助", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("c11x5Widget", "分析", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("c11x5Widget", "退出", None, QtGui.QApplication.UnicodeUTF8))
        self.action_plotRepeatNumber.setText(QtGui.QApplication.translate("c11x5Widget", "重复次数统计", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about.setText(QtGui.QApplication.translate("c11x5Widget", "关于", None, QtGui.QApplication.UnicodeUTF8))
        self.action_startAnalyse.setText(QtGui.QApplication.translate("c11x5Widget", "数据预分析", None, QtGui.QApplication.UnicodeUTF8))
        self.action_analyze_selected.setText(QtGui.QApplication.translate("c11x5Widget", "选中数据分析", None, QtGui.QApplication.UnicodeUTF8))
        self.action_draw_sample.setText(QtGui.QApplication.translate("c11x5Widget", "测试绘图", None, QtGui.QApplication.UnicodeUTF8))
        self.action_select_from_yestorday.setText(QtGui.QApplication.translate("c11x5Widget", "任选一个昨天数据", None, QtGui.QApplication.UnicodeUTF8))
        self.action_distribution_analyze.setText(QtGui.QApplication.translate("c11x5Widget", "概率分布特性", None, QtGui.QApplication.UnicodeUTF8))
        self.action_analyze_selected_distribution_local.setText(QtGui.QApplication.translate("c11x5Widget", "选中行局部分布", None, QtGui.QApplication.UnicodeUTF8))
        self.action_analyze_selected_distribution_global.setText(QtGui.QApplication.translate("c11x5Widget", "选中行全局分布", None, QtGui.QApplication.UnicodeUTF8))
        self.action_draw_distribution_animation.setText(QtGui.QApplication.translate("c11x5Widget", "分布动态变化特性", None, QtGui.QApplication.UnicodeUTF8))
        self.action_select_by_global.setText(QtGui.QApplication.translate("c11x5Widget", "按全局分布选", None, QtGui.QApplication.UnicodeUTF8))
        self.action_select_by_local.setText(QtGui.QApplication.translate("c11x5Widget", "按局部分布选", None, QtGui.QApplication.UnicodeUTF8))

